- hosts: target
  tasks:
    - name: create simple service template
      become: true
      template:
        src: web.rb
        dest: /usr/bin/ruby /home/vagrant/web.r
    - name: run samole service
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: sample
